### PR TITLE
Reduce comm counts for BlockDist.doiBulkTransfer

### PR DESCRIPTION
**Pull request by benharsh**

### CODE REVIEW

**Comment by benharsh** [comment]
@bradcray : this should resolve the comm count issues we were discussing earlier. Some tests now match the .good file, others are slightly improved. At some point, if we have the time, we should also do a run with cyclic and replicated to head off noise in nightly testing.

**Comment by bradcray** [comment]
Fast work, thanks!  Do you think the pending memory leaks fixes will further affect comm counts (positively or negatively)?  If not, I might update the .good files for tests that measure comm counts.  If so (or you're unsure), I'll hold off for now.

**Comment by benharsh** [comment]
I think we should wait to update the .good files until we have the correctness errors nailed down further. I'd like to avoid a noisy git history if possible.

**Comment by bradcray** [comment]
OK, sounds good.

**Pull request merged**
