### PR TITLE
Binary IO for DefaultRectangular and DR slices

### PR DESCRIPTION
**Pull request by benharsh**
Getting the rank-change and reindex cases to work seemed tricky, so I'm skipping them for now. This resolves the fasta performance regression. Testing came back as expected on --local.

### CODE REVIEW

**Comment by benharsh** [comment]
@bradcray : here you go!

**Comment by bradcray** [comment]
Great, thanks!  Could/should this be committed to master independent of the array views change?  (As usual, no pressure to do so, just asking.  I suspect it'd require at least some minor diffs similar to the ones our current branch has against the I/O routines on master).

**Comment by benharsh** [comment]
I'm not sure, but I'll look into it.

**Comment by bradcray** [comment]
(on chat, Ben clarified that it wasn't easily separable from the branch.

**Pull request merged**
